services:
  course-db:
    container_name: course-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always

  course-service:
    build: ./course-service
    image: course-service
